### ISSUE TITLE
ssh-keys

### ISSUE THREAD

**Issue by juasiepo** [mthibaut/puppet-users#2]
Can I use this module to provision ssh-keys too?
I have looked the setuo.pp and it doesn't says anything about ssh-keys.

Thank you

**Comment by mthibaut** [comment]
Hi,

The module will automatically provision an ssh key if none exists yet. If one does already exist (e.g. if you create it using some other means), then it will use the existing one instead.

## 

maarten

**Comment by juasiepo** [comment]
I have added the proper line "I think" to the hiera file
    shell: '/bin/bash'
      sskeys :
        **ssh-dss 'AAAAB3NzaC1kc3MAAACBA very long line here'**

But the ssh key is not provisioned. And nothing wrong appear in the puppet logs.

**Comment by mthibaut** [comment]
Oh I'm sorry I thought you were referring to a different module of mine. No, the users module doesn't setup ssh keys. Good idea though, maybe I will implement it later.

## 

maarten

**Comment by jerrac** [comment]
I'd like the ability to add ssh_authorized_keys to each user as well. I wouldn't want the module automatically creating the a key, though.

Something like:

``` yaml
users_sysadmins:
        john:
            ensure: present
            uid: 1000
            gid: staff
            groups: - wheel
            comment: John Doe
            managehome: true
            sshauthkeys:
                - keyone:
                    - type: ssh-rsa
                    - key: really long key
                - keytwo:
                    - type: ssh-rsa
                    - key: really long key
```

which would add ssh_authorized_key resources equivalent to:

``` puppet
ssh_authorized_key { 'keyone':
  ensure => present,
  key => "insertkeyhere",
  user => 'john',
  type => ssh-rsa,
  name => "keyone"
}
ssh_authorized_key { 'keytwo':
  ensure => present,
  key => "insertkeyhere",
  user => 'john',
  type => ssh-rsa,
  name => "keytwo"
}
```

**Comment by mthibaut** [comment]
Hi,

My latest commit now contains the functionality you requested. Can you give it a try before I update the module on puppetforge?

## 

maarten

**Comment by jerrac** [comment]
Just tried, but it doesn't look like the .ssh directory was even created.

Puppet didn't output errors. 

I just ran a puppet apply on my manifest.

Did you name the array of keys "sshauthkeys" like in my example? Or did you think about it more than I did and come up with something better?

``` json
"users_sysadmins": {
    "tester1": {
        "name": "tester1",
        "ensure": "present",
        "uid": "1001",
        "groups": "sudo",
        "comment": "Test One",
        "managehome": "true",
        "home": "/home/tester1",
        "sshauthkeys":[
                {"keyone": {"type": "ssh-rsa", "key": "really long key"}},
                {"keyone": {"type": "ssh-rsa", "key": "really long key"}}]
    },
    "tester": {
        "name": "test",
        "ensure": "present",
        "uid": "10044",
        "groups": "sudo",
        "comment": "test",
        "managehome": "true",
        "home": "/home/tester"
    }
}
```

**Comment by mthibaut** [comment]
David,

No, it's called ssh_authorized_keys - not sshauthkeys. I wanted to keep the same naming conventions as in puppet.

Like this:

```
            ssh_authorized_keys:
                    one:
                            type: 'ssh-rsa'
                            key: blabla
```

## 

maarten
